Updated C# Dev Kit FAQ
microsoft/vscode-docs pull request #6696
Opened 2023-09-28 19:47 UTC by mikadumont

2023-09-29 18:50 UTC, webreidi requested changes
Looks good. Just a couple of changes.

2023-09-29 18:50 UTC, webreidi commented on docs/csharp/cs-dev-kit-faq.md
> +C# Dev Kit supports building web apps, console apps, class library projects, and test projects for .NET Core, often also called .NET. The [.NET MAUI extension](https://marketplace.visualstudio.com/it
Add link to https://learn.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server on .NET Framework.

2023-09-29 18:50 UTC, webreidi commented on docs/csharp/cs-dev-kit-faq.md
> +You can either [update your project](https://learn.microsoft.com/en-us/dotnet/core/porting/) to an SDK-style project to use all available C# Dev Kit features. Or you can use the new Prefer CSharp Ext
This needs more details. Tell them how to set the setting (both options, with the toast or manually).

2023-10-02 18:10 UTC, webreidi commented on docs/csharp/cs-dev-kit-faq.md
> +Alternatively, you can use the new "Prefer CSharp Extension" workspace setting located in the Settings UI. This setting delegates solution and project load to the C# extension, but some C# Dev Kit fe
I think you should also mention about needing to reload once the setting has been applied for it to take effect.

2023-10-02 22:33 UTC, webreidi approved these changes

2023-10-02 23:27 UTC, gregvanl commented on docs/csharp/cs-dev-kit-faq.md
> +Note: If you are located in China the Great Firewall of China may be blocking your .NET download which can cause a timeout.
Are we allowed to say "Great Firewall of China"?
Might be better to say "If you are located in China, your .NET download may be blocked and cause a timeout."

2023-10-02 23:28 UTC, gregvanl commented on docs/csharp/cs-dev-kit-faq.md
> +Open the Output window and switch to the “Projects” pane to look for more information. You should see something like this:
Use bold for UI elements so keep `**Projects**`

2023-10-02 23:30 UTC, gregvanl commented on docs/csharp/cs-dev-kit-faq.md
> +![Point the .NET runtime acquisition extension to an existing .NET 7 install](images/faq/point-dotnet-runtime-to-existing-dotnet-install.png)
Better to use a code block for the settings JSON example than a screenshot.
That way users can easily copy and paste to get started

2023-10-03 01:27 UTC, gregvanl approved these changes

2023-10-03 01:28 UTC, merged