Adding documentation for nuget commands in C#DK
microsoft/vscode-docs pull request #7306
Opened 2024-05-21 20:53 UTC by albarry4

Changing the package management file to addin information about the new NuGet experience in C# Dev Kit

2024-05-21 23:22 UTC, ntrogh reviewed
@albarry4 Thanks for the update! Some formatting suggestions and ask to include alt text for images.

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +NuGet is the package manager for .NET. It defines how packages for .NET are created, hosted, and consumed, and provides the tools for each of those roles. You can manage your NuGet packages directly
```suggestion
NuGet is the package manager for .NET. It defines how packages for .NET are created, hosted, and consumed, and provides the tools for each of those roles. You can manage your NuGet packages directly from the C# Dev Kit Solution explorer and commands in the Command Palette. NuGet also manages the dependency tree on behalf of a project, so you only need to focus on the packages that you're directly using in a project. For more information, go to the [NuGet documentation](https://learn.microsoft.com/nuget/what-is-nuget).
```

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +In C# Dev Kit, you can perform NuGet package operations in either of two ways: commands in the command palette or through right-click actions in the C# Dev Kit solution explorer. The below documentat
```suggestion
In C# Dev Kit, you can perform NuGet package operations in either of two ways: commands in the Command Palette or through right-click actions in the C# Dev Kit Solution explorer. The below documentation details how to use each NuGet command through both of the two methods.
```

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +To add a NuGet package to your project, use the command “NuGet: Add NuGet Package”.
```suggestion
To add a NuGet package to your project, use the command **NuGet: Add NuGet Package**.
```

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +![alt text](images/package-management/nuget-command-addpackage.png)
Can you add a descriptive alt text for users that rely on it?

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +To update a NuGet package in your project, use the command “NuGet: Update NuGet Package”. If you have more than one project in your solution, you will be asked to select which project contains the pa
```suggestion
To update a NuGet package in your project, use the command **NuGet: Update NuGet Package**. If you have more than one project in your solution, you will be asked to select which project contains the package that you would like to update. Next, you will see a list of the packages that are currently installed in your project which have an update available. Choose which one you want to update. If no packages in your solution have an update available, you will see a message notifying you of this.
```

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +To remove a NuGet package from your project, use the command “NuGet: Remove NuGet Package.” If you have more than one project in your solution, you will be asked to select which project that you woul
```suggestion
To remove a NuGet package from your project, use the command **NuGet: Remove NuGet Package**. If you have more than one project in your solution, you will be asked to select which project that you would like to remove a package from.
```

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +NExt, you will see a list of the packages that are currently installed in your project and let you choose which one you want to remove. C# Dev Kit will then perform the necessary changes and update y
```suggestion
Next, you will see a list of the packages that are currently installed in your project and let you choose which one you want to remove. C# Dev Kit will then perform the necessary changes and update your project file and references.
```

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +
You might consider using a numbered list to make these steps more scannable.

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +
Similar, consider using a numbered list.

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +
Similar, consider using a numbered list.

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +![alt text](images\package-management\nuget-command-addackage-projectselection.png)
```suggestion
![alt text](images/package-management/nuget-command-addackage-projectselection.png)
```

2024-05-21 23:22 UTC, ntrogh commented on docs/csharp/package-management.md
> +![alt text](images/package-management\nuget-command-addpackage-search2.png)
```suggestion
![alt text](images/package-management/nuget-command-addpackage-search2.png)
```

2024-05-30 21:09 UTC, albarry4 commented
@ntrogh I just finished making those suggested changes -- would you be able to review again?

2024-05-30 22:07 UTC, ntrogh requested changes
Suggested some minor rewording and formatting fixes. Otherwise, should be good to go.

2024-05-30 22:07 UTC, ntrogh commented on docs/csharp/package-management.md
> +3. Next, you will see a list of the packages that are currently installed in your project which have an update available. Choose which one you want to update. If no packages in your solution have an
```suggestion
3. Next, choose which package to update from the list of packages that are currently installed in your project and that have an update available. If no packages in your solution have an update available, you see a message notifying you of this.
```

2024-05-30 22:07 UTC, ntrogh commented on docs/csharp/package-management.md
> +4. Finally, you will be able to select which version you would like to update the package to from a dropdown list of all available versions.
```suggestion
4. Finally, you can select which version you would like to update the package to from a dropdown list of available versions.
```

2024-05-30 22:07 UTC, ntrogh commented on docs/csharp/package-management.md
> +5. C# Dev Kit will then perform the necessary changes and update your project file and references.
```suggestion
5. C# Dev Kit then performs the necessary changes and updates your project file and references.
```

2024-05-30 22:07 UTC, ntrogh commented on docs/csharp/package-management.md
> +2. If you have more than one project in your solution, you will be asked to select which project that you would like to remove a package from.
```suggestion
2. If you have more than one project in your solution, you are asked to select which project that you would like to remove a package from.
```

2024-05-30 22:07 UTC, ntrogh commented on docs/csharp/package-management.md
> +3. Next, you will see a list of the packages that are currently installed in your project and let you choose which one you want to remove.
```suggestion
3. Next, choose which package you want to remove from the list of packages that are currently installed in your project.
```

2024-05-30 22:07 UTC, ntrogh commented on docs/csharp/package-management.md
> +4. C# Dev Kit will then perform the necessary changes and update your project file and references.
```suggestion
4. C# Dev Kit then performs the necessary changes and updates your project file and references.
```

2024-05-30 22:14 UTC, albarry4 commented
> Suggested some minor rewording and formatting fixes. Otherwise, should be good to go.

made all of those changes! :)

2024-05-30 22:29 UTC, ntrogh approved these changes

2024-05-30 22:32 UTC, merged