add faq about blocked extensions
microsoft/vscode-docs pull request #7311
Opened 2024-05-24 15:44 UTC by thispaul

2024-05-24 15:52 UTC, ntrogh commented
@isidorn can you also have a look at these changes?

2024-05-24 16:13 UTC, ntrogh requested changes
Slight rewording of the text.

2024-05-24 16:13 UTC, ntrogh commented on docs/copilot/faq.md
> +If you receive a message that a 3rd-party extension is blocked from using Copilot Chat, the extension was likely disabled due to a detected pattern of abuse coming from that specific extension. Pleas
```suggestion
If you receive a message that a third-party extension is blocked from using Copilot Chat, the extension was likely disabled due to a detected pattern of abuse coming from that specific extension. Contact the publisher of the extension when you encounter this issue. You can find the publisher information on the extension details page in the VS Code Marketplace.
```

2024-05-24 21:47 UTC, thispaul commented
cc @bamurtaugh

2024-05-24 22:37 UTC, bamurtaugh commented
Thanks @thispaul! LGTM, let's hear what @isidorn thinks too.

2024-05-27 09:32 UTC, isidorn requested changes
Looks good overall. Request some minor changes and then we can merge-in.

2024-05-27 09:32 UTC, isidorn commented on docs/copilot/faq.md
> +If you receive a message that a third-party extension is blocked from using Copilot Chat, the extension was likely disabled due to a detected pattern of abuse coming from that specific extension. Con
Can we not say "third-party". We do not want it to sound like 1st parties we treat specially.

So I suggest to just say "extension".

2024-05-27 09:32 UTC, isidorn commented on docs/copilot/faq.md
> +If you receive a message that a third-party extension is blocked from using Copilot Chat, the extension was likely disabled due to a detected pattern of abuse coming from that specific extension. Con
It is called "VS Marketplace", not "VS Code Marketplace"

2024-05-27 09:40 UTC, ntrogh commented on docs/copilot/faq.md
> +If you receive a message that a third-party extension is blocked from using Copilot Chat, the extension was likely disabled due to a detected pattern of abuse coming from that specific extension. Con
```suggestion
If you receive a message that an extension is blocked from using Copilot Chat, the extension was likely disabled due to a detected pattern of abuse coming from that specific extension. Contact the publisher of the extension when you encounter this issue. You can find the publisher information on the extension details page in the Visual Studio Marketplace.
```
```suggestion
If you receive a message that a third-party extension is blocked from using Copilot Chat, the extension was likely disabled due to a detected pattern of abuse coming from that specific extension. Contact the publisher of the extension when you encounter this issue. You can find the publisher information on the extension details page in the VS Code Marketplace.
```

2024-05-27 09:41 UTC, ntrogh approved these changes

2024-05-27 09:51 UTC, DonJayamanne approved these changes

2024-05-27 11:25 UTC, isidorn approved these changes

2024-05-27 11:26 UTC, merged