fix: add description for auto saving based on language
microsoft/vscode-docs pull request #7826
Opened 2024-11-27 23:33 UTC by cachandlerdev

I added a short explanation of how to customize the auto save feature for specific language types in accordance with [this issue](https://github.com/microsoft/vscode/issues/234769), since the feature is currently not mentioned in the documentation or in the Settings GUI.

2024-12-09 20:35 UTC, ntrogh requested changes
@cachandlerdev thanks for updating the docs. Just added some text suggestions.

2024-12-09 20:35 UTC, ntrogh commented on docs/editor/codebasics.md
> +If you want to customize `Auto Save` features for specific languages or file types, you can do so from your `setting.json` by adding language specific rules. For example, you could disable `Auto Save
```suggestion
If you want to customize the `Auto Save` functionality for specific languages or file types, you can do so from the `settings.json` file by adding language-specific rules. 

For example, to disable `Auto Save` for LaTeX files:

```

2024-12-10 02:08 UTC, cachandlerdev commented
I have made the changes as requested.

2024-12-10 10:05 UTC, ntrogh approved these changes
@cachandlerdev thanks for contributing to our docs!

2024-12-10 10:07 UTC, lszomoru approved these changes

2024-12-10 13:56 UTC, merged