Update vuejs-tutorial.md
microsoft/vscode-docs pull request #7890
Opened 2024-12-24 16:11 UTC by MooseSaeed

This pull request includes updates to the Vue.js tutorial documentation in Visual Studio Code. The changes focus on updating extension recommendations, improving clarity, and ensuring the tutorial content is current.

### Vue 2 Support:
- Changed the Vue 2 Support note to past tense to reflect that it has ended.

### Extension Recommendations:
- Updated references to the "Vue - Official" extension, previously known as Volar, for better IntelliSense, TypeScript support, and formatting.

### Vue CLI Reference:
- Removed the reference to `vue-cli-service` as it's no longer recommended for new apps and isn't relevant to the tutorial.
- Added information about Vite's Hot Module Replacement feature to improve the development experience.

### Tutorial Content:
- Clarified instructions for running the Vue application and removed redundant steps.
- Enhanced the "Go to Definition" and "Peek Definition" sections to provide clearer instructions on using these features with the Vue - Official extension.
- Removed unnecessary step to restart the dev server, as Vite's HMR automatically applies the changes.

### Debugging and Linting:
- Updated links for the Vue ESLint plugin and vue-devtools to provide users with the latest official resources.

### Helpful External Link:
- Added a link to a video tutorial on using the Vue - Official extension in VS Code.

2024-12-24 16:43 UTC, MooseSaeed commented
> @microsoft-github-policy-service agree

2025-01-02 10:44 UTC, ntrogh requested changes
@MooseSaeed Thanks for updating the Vue.js tutorial. Looks good except for the linking to third-party learning content.

2025-01-02 10:44 UTC, ntrogh commented on docs/nodejs/vuejs-tutorial.md
> +[Vue - Official extention](https://vueschool.io/lessons/volar-the-official-language-feature-extension-for-vs-code) is only one of many Vue.js extensions available for VS Code.
Typo: extention => **extension**

Suggest using the Marketplace URL for the extension. We don't usually link to third-party learning content from our docs unless they're part of the core product. So, it's fine to link to vuejs.org content.

2025-01-17 09:14 UTC, ntrogh approved these changes

2025-01-17 09:15 UTC, merged